name: Predictor

on:
  workflow_dispatch: # To trigger the action from REST API

jobs:
  predict:
    environment: production
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm ci

      - name: Predict
        run: npm run predict
        env:
          DB_URL: ${{ secrets.DB_URL }}
          TELEGRAM_API_TOKEN: ${{ secrets.TELEGRAM_API_TOKEN }}
          DB_NAME: ${{ vars.DB_NAME }}
          DB_COLLECTION: ${{ vars.DB_COLLECTION }}
          TELEGRAM_CHAT_ID: ${{ vars.TELEGRAM_CHAT_ID }}
          GOLD_RETAIL_PRICE_API_URL: ${{ vars.GOLD_RETAIL_PRICE_API_URL }}
          GOLD_MARKET_PRICE_API_URL: ${{ vars.GOLD_MARKET_PRICE_API_URL }}
